language: node_js

sudo: false

node_js:
  # https://github.com/nodejs/LTS
  - "8" # ends December 2019
  - "10" # ends April 2021
  - "12" # ends April 2022

env:
  global:
    - SAUCE_USERNAME=sinonjs
    - secure: "Szc/biR+MJFC/r4IFzDVXJkIt1COglrCyCd/drmBrXj4AE70J2qn8QlU0n3uQUhrDH5k0NtSWnZHcfxuUTHpasvh9yPFGtqnNeqgftZjXQyJFS+rYye4i04cyYGEmc1qxhpljfAXbvCJV+bHDFmWxIF6KSHWMsVk6IbhoD0/Dis="

before_install:
  # Prevent mochify -> puppeteer install script to run unnecessarily
  - if [ "x$TRAVIS_NODE_VERSION" != "x8" ]; then npm config set ignore-scripts true; fi

before_script:
  # Make npm run work for the script phase:
  - if [ "x$TRAVIS_NODE_VERSION" != "x8" ]; then npm config set ignore-scripts false; fi

script:
  - npm run test-node
  - if [ "x$TRAVIS_NODE_VERSION" = "x8" ]; then npm run lint; fi
  - if [ "x$TRAVIS_NODE_VERSION" = "x8" ]; then npm run test-headless -- --allow-chrome-as-root; fi
  - if [ "x$TRAVIS_NODE_VERSION" = "x8" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then npm run test-cloud; fi
